server:
  port: 8083

spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://localhost:5432/vbank_transactions
    username: vbank
    password: vbank
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  http:
    client:
      connect-timeout: 2s
      read-timeout: 5s
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        max.block.ms: 2000

services:
  account:
    base-url: http://localhost:8082