server:
  port: 8084

spring:
  application:
    name: bff-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        max.block.ms: 2000

vbank:
  services:
    user: http://localhost:8081
    account: http://localhost:8082
    transaction: http://localhost:8083
