server:
  port: 8084

spring:
  application:
    name: bff-service
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        max.block.ms: 2000

vbank:
  services:
    user: ${USER_SERVICE_URL:http://localhost:8081}
    account: ${ACCOUNT_SERVICE_URL:http://localhost:8082}
    transaction: ${TRANSACTION_SERVICE_URL:http://localhost:8083}
