server:
  port: 8082

spring:
  application:
    name: account-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/vbank_accounts}
    username: vbank
    password: vbank
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        max.block.ms: 2000